# config for hybrid a star
  steering_angle_num: 5 # steering angle discrete
  dt: 0.6 # s used for compute trajectory distance while expanding nodes
  Benchmark_path: BenchmarkCases # case folder name
  trajectory_dt: 0.2 # s discrete the trajectory for collision check
  map_discrete_size: 0.1 # m
  flag_radius: 18 # m (in this circle area, we use rs curve to connect goal pose)
  extended_num: 1 # extend point at the end of orignal path

  # collision check
  safe_side_dis: 0.1 # m
  safe_fr_dis: 0.1 # m
  collision_check: distance # circle or distance, choose a method for collision check
  draw_collision: False # draw collision position while searching new nodes

  # m expand distance for path optimization
  expand_dis: 0.8
  # weight used for path optimization
  smooth_cost: 5
  compact_cost: 3
  offset_cost: 0.8
  slack_cost: 1

  # velocity plan dt
  velocity_plan_dt: 0.05 # s

